
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ashleyreardon.github.io/alr/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/alr"

# Google tracking id

google-tracking-id: "UA-112552430-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Ashley Reardon"
title: "Ashley L Reardon"
description: "Professional website of Ashley Reardon, human performance researcher and gaming enthusiast"
keywords: "reardon, ashley, human performance, research, gaming"
#favicon: "/img/favicon1.ico"
favicon: "/img/favicon1.ico" 

################
# Header layout #
################

black-favicon: "/img/favicon1.ico"

background-img: "../img/ffs.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Life begins at the end of your comfort zone."
  - text: "Where’s your will to be weird?"

me-img: "/img/author1.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False #was true

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  #- image: "/img/timeline/spidertocat.png"
  - image: "/img/timeline/research.jpg"
    date: "May 2017 - Present"
    description: "<b>Quantum Improvements Consulting</b>
    
    \
    
    ."
    <small>
<b>Publications:</b>
</small>

<b>Reardon, A.</b>, Abich, J., Murphy, J., Hannigan, F. (2018). <a href="http://www.modsimworld.org/papers/2018/MODSIM_2018_Paper_not_required_for_a_23.pdf">Evolution of Green Pig: Best practices in mobile app design.  Paper presented at MODSIM World, Norfolk, VA.


<b>Reardon, A.</b>, Volante, W., Sanders, T., & Hancock, P. (2016). <a href="http://tg.hfes.org/actg/pdfs/ACTG%202016%20Newsletter.pdf">Implicit measures as a calibration tool for the symbiotic human/robot system</a>.  AugCog Technical Group, 9 (1), 7-8.


<b>Reardon, A.</b>, Volante, W., Sanders, & Hancock, P. A. (August, 2016). Using an implicit association test to reveal hidden biases toward robots. Paper presented at the 124th Annual American Psychological Association Convention, Denver, CO.


Sanders, T. L., Schafer, K. E., Volante, W., <b>Reardon, A.</b>, & Hancock, P. A. (September, 2016). <a href="http://journals.sagepub.com/doi/pdf/10.1177/1541931213601400">Implicit attitudes toward robots</a>. Proceedings of the Human Factors and Ergonomics Society Annual Meeting (Vol. 60, No. 1, pp. 1746-1749). SAGE Publications.


Volante, W. G., Sanders, T., <b>Reardon, A.</b>, & Hancock, P. (April, 2016). <a href="https://commons.erau.edu/cgi/viewcontent.cgi?article=1143&context=hfap">Do you know if you trust a robot? Influences that mediate implicit and explicit trust</a>. Poster presented at the 10th Human Factors & Applied Psychology Student Conference, Daytona Beach, FL.


# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "reardona@knights.ucf.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author1.jpg"

##################
# Social Buttons #
##################

social:
  #- title: "facebook"
    #url: "https://facebook.com/"
  #- title: "twitter"
    #url: "https://twitter.com/"
  #- title: "github"
    #url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  #- title: "bitcoin"
    #url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
    #url: "/feed.xml"
   - title: "linkedin"
     url: "https://linkedin.com/in/ashleylaurenreardon/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Portfolio: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
